version: '3'

services:
  web:
    container_name: "circleci-experiment_web"
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_APP: src/controller.py
      FLASK_DEBUG: development
