version: '3'

services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      FLASK_APP: src/controller.py
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vitus
      MYSQL_DATABASE: vp_db
      MYSQL_USER: vitus
      MYSQL_PASSWORD: vitus
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 10
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   depends_on:
  #     - web
  #   restart: always
