version: '3'

services:
  web:
    container_name: "circleci-experiment_web"
    build: .
    ports:
      - 8080
    volumes:
      - .:/app
    environment:
      FLASK_APP: src/controller.py
      FLASK_DEBUG: development
# nginx:
#     image: nginx:latest
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - /etc/letsencrypt:/etc/letsencrypt
#     depends_on:
#       - app
#     restart: always
