jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependency
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest test.py
workflows:
  version: 2
  test:
    jobs:
      - test
    workspaces:
      create-pr:
        paths:
          - .
      check-pr:
        requires:
          - test
        filters:
          branches:
            only: main
        parallelism: 1
        steps:
          - attach_workspace:
              at: .
          - run:
              name: Check if all tests passed
              command: |
                if grep -q "FAILED" test-results.txt; then
                  echo "Some tests failed, cannot merge!"
                  exit 1
                else
                  echo "All tests passed, ready to merge!"
                fi
