jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: mkdir ./test-results
      - run:
          name: Install dependency
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Debug
          command: |
            pwd
            ls -lart ./src/templates/
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest ./tests/test_controller.py --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh -oStrictHostKeyChecking=no -v $USER@$IP "cd CircleCI-Experiment/; ./deploy.sh"

workflows:
  version: 2
  check-pr: 
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main