jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependency
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest test.py
workflows:
  version: 2
  check-pr: 
    jobs:
      - test
          filters: 
            branches:
              only:
                - /initial-ci-*/